data_arguments:
  data_dir: /home/ubuntu/new_breast_svs
  data_dir_key: None
  label_dict:
    high_expreession_genes: 1
    low_expression_genes: 0
  preset: presets/tcga.csv
  process_list: heatmap_demo.csv
  slide_ext: .svs
encoder_arguments:
  model_name: uni_v1
  target_img_size: 224
exp_arguments:
  batch_size: 256
  n_classes: 2
  production_save_dir: heatmaps/heatmap_production_results_MMP3
  raw_save_dir: heatmaps/heatmap_raw_results_MMP3
  save_exp_code: HEATMAP_OUTPUT
heatmap_arguments:
  alpha: 0.4
  binarize: false
  binary_thresh: -1
  blank_canvas: false
  blur: false
  calc_heatmap: true
  cmap: jet
  custom_downsample: 1
  save_ext: jpg
  save_orig: true
  use_center_shift: true
  use_ref_scores: true
  use_roi: false
  vis_level: 1
model_arguments:
  ckpt_path: /home/ubuntu/XpressO/Classification/results/gene_exp_100_s1/s_6_checkpoint.pt
  drop_out: 0.0
  embed_dim: 1024
  initiate_fn: initiate_model
  model_size: small
  model_type: clam_sb
  n_classes: 2
patching_arguments:
  custom_downsample: 1
  overlap: 0.5
  patch_level: 0
  patch_size: 256
sample_arguments:
  samples:
  - k: 10
    mode: topk
    name: topk_high_attention
    sample: true
    seed: 1
